config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  get 'home', to: 'pages#home', as: :home

  get 'influencers_home', to: 'pages#influencers_home', as: :influencers_home

  get 'businesses_home', to: 'pages#businesses_home', as: :businesses_home

  get 'businesses/profile', to: 'businesses#profile', as: :business_profile
  resources :businesses

  resources :campaigns do
    resources :applications, only: [:index, :show, :new, :create, :edit, :update]
  end

  resources :influencers

  get 'my_influence', to: "influencers#me"

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :find_business, only: [:show, :edit, :update, :destroy, :profile]

  def index
    @businesses = policy_scope(Business)
  end

  def new
    @business = Business.new
    authorize @business
  end

  def create
    @business = Business.new(business_params)
    @business.user = current_user
    authorize @business
    if @business.save
      flash[:notice] = "Welcome Aboard, #{@business.name}!"
      redirect_to business_path(@business)
    else
      flash[:alert] = "Invalid parameters, try again"
      redirect_to new_business_path
    end
  end

  def show
    authorize @business
  end

  def edit
    authorize @business
  end

  def update
    @business.update(business_params)
    authorize @business
    redirect_to business_path(@business)
  end

  def destroy
    @business.destroy
    authorize @business
    flash[:notice] = "Bye #{@business.name}, All the best!"
    redirect_to root_path
  end

  def profile
    authorize @business
  end


  private

  def find_business
    @business = Business.find_by_user_id(current_user)
  end

  def business_params
    params.require(:business).permit(:name, :address, :category, :tva, :contact_name, :photo, :photo_cache)
  end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_business_form.html.erb
<%= simple_form_for(@business) do |f| %>
  <%= f.error_notification %>

  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :category %>
  <%= f.input :tva %>
  <%= f.input :contact_name %>
  <%= f.input :photo, label: 'Logo' %>
  <%= f.input :photo_cache, as: :hidden %>

  <div class="text-center">
  <%= f.button :submit, class: "brand-button" %>
  </div>
<% end %>

app/views/businesses/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">

      <div class="form-container">
      <h1>Update your business profile</h1>
      </div>

      <%= render 'business_form' %>
    </div>
  </div>
</div>

app/views/businesses/index.html.erb
<div class="container">

  <h1 class="text-center" style="margin-bottom: 30px"> Businesses </h1>
  <% @businesses.each do |business| %>
  <div class="business-card-container">
    <p><%= business.name%></p>
    <div class="business-card-banner" style="background-image: url('http://www.brianhonigman.com/wp-content/uploads/2014/06/tumblr_mucr5ouPLQ1s8jl6ro1_400.gif');"></div>
    <p> #<%= (business.category).split.join %> </p>
    <hr class="line">
    <%= link_to business_path(business), class: "business-link" do %>
    <i class="fa fa-heart-o"></i>    Love it? Check it!
    <% end %>

  </div>
  <% end %>

</div>

app/views/businesses/new.html.erb
<div class="container">
  <div class="row">
    <div class="form-container col-sm-6 col-sm-offset-3">

      <div class="text-center">
      <h3>Register your Business</h3>
      </div>

      <%= render 'business_form' %>

    </div>
  </div>
</div>

app/views/businesses/profile.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 container-instagram">
      <div class="insta-pic col-xs-7">
      </div>
      <div class="col-xs-4 insta-description">
        <h1><%=@business.name%></h1>
        <h4>Contact</h4>
        <p><%= @business.contact_name%> </p>
        <h4>Address</h4>
        <p><%= @business.address %></p>

      </div>
    </div>
  </div>
  <div class="btn text-center">
  <%= link_to "  Profile  ", edit_business_path(@business), class: "insta-business-edit"%>
  <%= link_to "  Delete  ", business_path(@business), method: :delete, class: "insta-business-delete"%>
  </div>
</div>

app/views/businesses/show.html.erb
<div class="banner insta-banner" style="background-image: linear-gradient(rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.2)), url('<%= @business.photo%>') ">
  <div class="banner-content">
    <h1 class="text-center insta-business-name"><%=@business.name%></h1>
  </div>
</div>

<div>

  <div class="tabs">
    <a class="tab active" data-target="#my_campaigns_wrapper">
      <h3><i class="fa fa-bullhorn"></i>  My Campaigns</h3>
    </a>
    <a class="tab" data-target="#analytics_wrapper">
      <h3><i class="fa fa-line-chart"></i>  Analytics</h3>
    </a>
  </div>

  <div id="my_campaigns_wrapper" class="tab-content">

    <% if @business.campaigns.present? %>

    <% (@business.campaigns).each do |campaign| %>

    <div class="insta-business-card-container">
      <div class="insta-pic-business-show" style="background-image: linear-gradient(rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4)), url('<%= campaign.photo %>');">
        <div class='insta-budget-container'>
          <div class='insta-budget'>
            <%= campaign.budget %>€
          </div>
        </div>
        <div class='insta-product'><%=campaign.product%></div>
      </div>
      <div class="business-insta-description">
        <div class='insta-title'>
          <%= link_to campaign.title, campaign_path(campaign) %>
        </div>
        <div class='insta-instruction'>
          <%=campaign.instructions%>
        </div>
        <div class='insta-timeline'>
          <div class='insta-timeline-start'>
            <i class="fa fa-flag-o insta-flag" aria-hidden="true"></i> <%= campaign.start_time %>
          </div>
          <div class="insta-timeline-line">
            <hr class="insta-timeline-color">
          </div>
          <div class='insta-timeline-end'>
            <i class="fa fa-flag-checkered insta-flag" aria-hidden="true"></i> <%= campaign.end_time %>
          </div>
        </div>
        <div class="insta-obligations">
          You will have to take <strong><%=campaign.pics_to_upload%></strong> photos, the brand will select <strong><%=campaign.pics_to_post%></strong> that you will need to upload.
        </div>

        <div class='insta-appliers-title'><h4>Applicants</h4></div>
        <div class='insta-appliers'>
          <%(campaign.applications).each do |application| %>

          <%= link_to image_tag(application.influencer.photo, { "data-id-app": application.id,"data-id-cpgn": application.campaign.id, class:"avatar-large insta-applier-item" }), "#" %>

          <% end %>
        </div>
      </div>
    </div>

    <% end %>

    <% else %>

    <div class="text-center">
      <p>You have no campaigns yet !</p>
      <%= link_to "Create a campaign", new_campaign_path, class: 'btn brand-button' %>
    </div>

    <% end %>

  </div>



  <div id="analytics_wrapper" class="tab-content hidden">

    <!-- Code pour la tab Analytics ici -->

  </div>

</div>