config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  get 'home', to: 'pages#home', as: :home

  get 'influencers_home', to: 'pages#influencers_home', as: :influencers_home

  get 'businesses_home', to: 'pages#businesses_home', as: :businesses_home

  get 'businesses/profile', to: 'businesses#profile', as: :business_profile
  resources :businesses

  resources :campaigns do
    resources :applications, only: [:index, :show, :new, :create, :edit, :update]
  end

  resources :influencers

  get 'my_influence', to: "influencers#me"

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

end

app/models/application.rb
class Application < ActiveRecord::Base
  belongs_to :campaign
  belongs_to :influencer
  validates :motivation, presence: true
  # validates :photo, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  include Pundit

  after_action :verify_authorized, except: :index, unless: :devise_controller?
  after_action :verify_policy_scoped, only: :index, unless: :devise_controller?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  def after_sign_in_path_for(resource)
    if(resource.influencer?)
      campaigns_path
    else
      if(resource.business)
        business_path(resource.business)
      else
        new_business_path
      end
    end
  end

  def default_url_options
    { host: ENV['HOST'] || 'localhost:3000' }
  end
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :find_application, only: [:show, :edit, :update]
  before_filter :disable_nav, only: [:show]
  before_filter :disable_footer, only: [:show]
  def index
    @applications = policy_scope(Application)
  end

  def show
    authorize @application
    @campaign = @application.campaign
    if @application == nil
      redirect_to campaign_path(@campaign)
    end

    # render :show, layout: false
  end

  def new
    @application = Application.new
    authorize @application
  end

  def create
    @influencer = Influencer.find_by_user_id(current_user)
    @campaign = Campaign.find(params[:campaign_id])
    @application = Application.new(application_params)
    authorize @application
    @application.campaign = @campaign
    @application.influencer = @influencer
    @application.status = "Pending"
    if @application.save
      flash[:notice] = "Thanks #{@influencer.username}, you've just applied for #{@campaign.title}. Your application is under review, we'll get back to you shortly"
      redirect_to campaign_path(@campaign)
    else
      flash[:alert] = "Failed to create an application, try again"
      redirect_to campaign_path(@campaign)
    end
  end

  def edit
    authorize @application
  end

  def update
    @application.update(application_params)
    authorize @application
    redirect_to business_path(@application.campaign.business)
  end

  def disable_nav
    @disable_nav = true
  end

  def disable_footer
    @disable_footer = true
  end

  private

  def application_params
    params.require(:application).permit(:motivation, :status)
  end

  def find_application
    @application = Application.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/views/applications/_application_form.html.erb
<%= simple_form_for [@campaign, @application] do |f| %>
  <%= f.error_notification %>

  <%= f.input :motivation, as: :text  %>

  <div class="text-center">
  <%= f.button :submit, class: "brand-button" %>
  </div>
<% end %>

app/views/applications/create.html.erb
<h1>Applications#create</h1>
<p>Find me in app/views/applications/create.html.erb</p>

app/views/applications/index.html.erb
<h1 class="text-center" style="margin-bottom: 30px"> Applications </h1>


<% @applications.each do |app| %>
  <div class="business-card-container">
    <p><%= app.influencer.username %></p>
    <div class="business-card-banner" style="background-image: url('http://www.brianhonigman.com/wp-content/uploads/2014/06/tumblr_mucr5ouPLQ1s8jl6ro1_400.gif');"></div>
    <p> #<%= Tag.find(app.influencer_id).name %> </p>
    <hr class="line">
    <%= link_to campaign_application_path(Campaign.find(app.campaign_id), app), class: " business-link brand-button" do%>
        <i class="fa fa-heart-o"></i>    Love it? Check it!
    <% end %>
  </div>
<% end %>

app/views/applications/show.html.erb
<div class="main-container">

  <div class="app-show-container">

    <div class="influencer-card">
      <div class="appliers-pres">
        <div class="applier-avatar-large">
         <%= image_tag @application.influencer.photo, class: "avatar-large" %>
       </div>
       <div class="applier-first-name">
       <p><%= @application.influencer.first_name %></p>
       </div>
<div class="display-middle-flex"></div>
       <div class="padding-text followers">
         <span><i class="fa fa-users"></i><%= @application.influencer.followers %></span>
       </div>
     </div>

     <!--  -->
     <div id="cf7">
      <% pics = Pic.order(likes: :desc).where("influencer_id = ?", @application.influencer.id).limit(3) %>
      <div class="app-top-pic-container opaque" style="background: url('<%= pics[0].pic_url %>')";>
        <span> <i class="fa fa-heart-o opaque" ></i> <%= pics[0].likes %></span>
      </div>
      <div class="app-top-pic-container" style="background: url('<%= pics[1].pic_url %>')";>
        <span> <i class="fa fa-heart-o" ></i> <%= pics[1].likes %>
        </span>
      </div>
      <div class="app-top-pic-container" style="background: url('<%= pics[2].pic_url %>')";>
       <span>  <i class="fa fa-heart-o" ></i> <%= pics[2].likes %>
       </span>
     </div>
   </div>



   <div id="cf7_controls">
    <span class="selected"><i class="fa fa-circle-o"></i></span>
    <span><i class="fa fa-circle-o"></i></span>
    <span><i class="fa fa-circle-o"></i></span>
  </div>



  <div>

    <div class="line-break"></div>
    <div class="padding-text top-tags">
     <span>Top Hashtags
       <% Tag.where("influencer_id = ?", @application.influencer.id).group(:name).order(count: :desc).limit(3).count.each do |t| %>
     </span><span>#<%= t[0] %>
     <% end %>
   </span>
 </div>
 <div class="average-wrapper">

   <div class="padding-text top-places">
     <span>Top Places </span>
     <ul class="list-places">
       <% Place.where("influencer_id = ?", @application.influencer.id).group(:name).order(count: :desc).limit(3).count.each do |t| %>
       <li>@<%= t[0] %></li>
       <% end %>

     </ul>
   </div>
   <div class="padding-text average">
     <span>On Average</span>
     <ul class="list-places">
       <li><i class="fa fa-heart-o"></i> <%= @application.influencer.avg_photo_likes
         %>
       </li>
       <li><i class="fa fa-comment-o"></i> <%= @application.influencer.avg_photo_comments
         %>
       </li>


     </ul>
   </div>

 </div>
 <div class="padding-text motivation">
   <span>Motivation</span><div><%= @application.motivation %></div>
 </div>

 <div class="info-container">


   <div class="app-show-status form-container">
     <!-- <div>
       <h4>Status</h4>
       <%# if @application.status == "Pending" %>
       <p><%= @application.status %></p>
       <%# else %>
       <p><%= @application.status %>ed</p>
       <%# end%>
     </div>
     <div> -->

       <%= simple_form_for [@campaign, @application], method: :put, url: campaign_application_path(@campaign, @application), :html => {class: 'form-inline order-2 text-center'} do |f| %>
       <%= f.error_notification %>
       <%= f.input :status, :as => :hidden, :input_html => { :value => "Accept" }  %>
       <%= button_tag(type: 'submit', class: "submission is-green") do %>
       <i class="fa fa-check"></i>
       <% end %>
       <% end %>

       <%= simple_form_for [@campaign, @application], method: :put, url: campaign_application_path(@campaign, @application), :html => {class: 'form-inline text-center'} do |f| %>
       <%= f.error_notification %>
       <%= f.input :status, :as => :hidden, :input_html => { :value => "Reject" }  %>
       <%= button_tag(type: 'submit', class: "submission is-red") do %>
       <i class="fa fa-remove"></i>
       <% end %>
       <% end %>
     </div>
   </div>
 </div>

</div>




</div>


</div>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>