config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  get 'home', to: 'pages#home', as: :home

  get 'influencers_home', to: 'pages#influencers_home', as: :influencers_home

  get 'businesses_home', to: 'pages#businesses_home', as: :businesses_home

  get 'businesses/profile', to: 'businesses#profile', as: :business_profile
  resources :businesses

  resources :campaigns do
    resources :applications, only: [:index, :show, :new, :create, :edit, :update]
  end

  resources :influencers

  get 'my_influence', to: "influencers#me"

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible slideDown" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible slideDown" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="site-footer">
    <div class="wrapperFull wrapperFull-dark">
      <div class="wrapper wrapper-thin section">
        <div class="text-group text-center">
          <ul class="footer-navigation">
            <li>
              <%= link_to "Home", home_path %>
            </li>
            <li>
              <%= link_to "Businesses", businesses_home_path %>
            </li>
            <li>
              <%= link_to "Influencers", influencers_home_path %>
            </li>
            <li>
              <%= link_to "About us", home_path %>
            </li>
          </ul>
          <ul class="social-list">
            <li>
              <%= link_to "https://twitter.com/Pic_Reward" do %><i class="fa fa-twitter-square" aria-hidden="true"></i><% end %>
            </li>
            <li>
              <%= link_to "http://instagram.com/pic_reward" do %><i class="fa fa-instagram" aria-hidden="true"></i><% end %>
            </li>
            <li>
              <%= link_to "https://www.facebook.com/picreward" do %><i class="fa fa-facebook-square" aria-hidden="true"></i><% end %>
            </li>
          </ul>
          <p>PICREWARD, CONNECTING BRANDS WITH INFLUENCERS</p>
        </div>
      </div>
    </div>
    <div class="wrapperFull wrapperFull-brand">
      <div class="wrapper wrapper-thin section section-short text-center">
        <p>&copy; PicReward. All Rights Reserved.</p>
      </div>
    </div>
  </footer>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag "piclogo.png", size: "100x60" %>
  <% end %>

  <p class="navbar-picreward">PicReward</p>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
   <!--  <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>
 -->
    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">

        <% if current_user.influencer %>

        <%= cl_image_tag current_user.influencer.photo, width: 50, height: 50, crop: :fill, class: "avatar-bordered dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to influencer_path(current_user) do %>
            <i class="fa fa-user"></i> <%= t ".profile", default: "My Dashboard" %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
            <% end %>
          </li>
        </ul>

        <% elsif current_user.business %>

        <%= cl_image_tag current_user.business.photo, width: 50, height: 50, crop: :fill, class: "avatar-bordered dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to new_campaign_path do %>
            <i class="fa fa-bullhorn"></i> <%= t ".profile", default: "Create campaign" %>
            <% end %>
          </li>
          <li>
            <%= link_to business_profile_path(current_user) do %>
            <i class="fa fa-user"></i> <%= t ".profile", default: "My Profile" %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
            <% end %>
          </li>
        </ul>

        <% else %>

        <p class="dropdown-toggle", id="navbar-wagon-menu", data-toggle="dropdown">Dashboard</p>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to new_business_path(current_user) do %>
            <i class="fa fa-user"></i> <%= t ".profile", default: "Register" %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
            <% end %>
          </li>
        </ul>

        <% end %>

      </div>
    </div>

    <% else %>

    <!-- Login text link -->
    <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item brand-button btn" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <% if user_signed_in? && current_user.influencer %>
      <%= link_to t(".top_call_to_action", default: "See Jobs"), campaigns_path, class: "navbar-wagon-item brand-button btn" %>
    <% elsif user_signed_in? && current_user.business.present? %>
      <%= link_to t(".top_call_to_action", default: "Dashboard"), business_path(current_user), class: "navbar-wagon-item brand-button btn" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">

        <% if user_signed_in? && current_user.influencer %>
          <li>
            <%= link_to influencer_path(current_user) do %>
            <i class="fa fa-user"></i> <%= t ".profile", default: "My Dashboard" %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
            <% end %>
          </li>

        <% elsif user_signed_in? && current_user.business %>
          <li>
            <%= link_to business_path(current_user) do %>
            <i class="fa fa-user"></i> <%= t ".profile", default: "My Dashboard" %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
            <% end %>
          </li>

        <% else %>

          <li>
            <%= link_to new_user_session_path do %>
            <i class="fa fa-sign-in"></i>  <%= t ".sign_in", default: "Login" %>
            <% end %>
          </li>

        <% end %>

      </ul>
    </div>
  </div>
</div>

app/views/shared/_transparent_navbar.html.erb
<div class="transparent-navbar-wagon navbar-wagon-fixed">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag "piclogo.png", size: "100x60" %>
  <% end %>

  <p class="navbar-picreward">PicReward</p>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
   <!--  <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>
 -->
    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">

        <% if current_user.influencer %>

        <%= cl_image_tag current_user.influencer.photo, width: 50, height: 50, crop: :fill, class: "avatar-bordered dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to influencer_path(current_user) do %>
            <i class="fa fa-user"></i> <%= t ".profile", default: "My Dashboard" %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
            <% end %>
          </li>
        </ul>

        <% elsif current_user.business %>

        <%= cl_image_tag current_user.business.photo, width: 50, height: 50, crop: :fill, class: "avatar-bordered dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to business_path(current_user) do %>
            <i class="fa fa-user"></i> <%= t ".profile", default: "My Dashboard" %>
            <% end %>
          </li>
          <li>
            <%= link_to business_profile_path(current_user) do %>
            <i class="fa fa-user"></i> <%= t ".profile", default: "My Profile" %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
            <% end %>
          </li>
        </ul>

        <% else %>

        <p class="dropdown-toggle", id="navbar-wagon-menu", data-toggle="dropdown">Dashboard</p>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to new_business_path(current_user) do %>
            <i class="fa fa-user"></i> <%= t ".profile", default: "Register" %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
            <% end %>
          </li>
        </ul>

        <% end %>

      </div>
    </div>

    <% else %>

    <!-- Login text link -->
    <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item brand-button brand-button-transparent btn" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <% if user_signed_in? && current_user.influencer %>
      <%= link_to t(".top_call_to_action", default: "See Jobs"), campaigns_path, class: "navbar-wagon-item brand-button brand-button-transparent btn" %>
    <% elsif user_signed_in? && current_user.business.present? %>
      <%= link_to t(".top_call_to_action", default: "Dashboard"), business_path(current_user), class: "navbar-wagon-item brand-button brand-button-transparent btn" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">

        <% if user_signed_in? && current_user.influencer %>
          <li>
            <%= link_to influencer_path(current_user) do %>
            <i class="fa fa-user"></i> <%= t ".profile", default: "My Dashboard" %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
            <% end %>
          </li>

        <% elsif user_signed_in? && current_user.business %>
          <li>
            <%= link_to business_path(current_user) do %>
            <i class="fa fa-user"></i> <%= t ".profile", default: "My Dashboard" %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
            <% end %>
          </li>

        <% else %>

          <li>
            <%= link_to new_user_session_path do %>
            <i class="fa fa-sign-in"></i>  <%= t ".sign_in", default: "Login" %>
            <% end %>
          </li>

        <% end %>

      </ul>
    </div>
  </div>
</div>