config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  get 'home', to: 'pages#home', as: :home

  get 'influencers_home', to: 'pages#influencers_home', as: :influencers_home

  get 'businesses_home', to: 'pages#businesses_home', as: :businesses_home

  get 'businesses/profile', to: 'businesses#profile', as: :business_profile
  resources :businesses

  resources :campaigns do
    resources :applications, only: [:index, :show, :new, :create, :edit, :update]
  end

  resources :influencers

  get 'my_influence', to: "influencers#me"

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  belongs_to :business
  has_many :applications
  mount_uploader :photo, PhotoUploader
  geocoded_by :target_location
  after_validation :geocode, if: :target_location_changed?
  validates :reward_type, presence: true
  validates :title, presence: true
  validates :product, presence: true
  validates :goal, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :description, presence: { message: "Description is mandatory, please specify one" }, length: {minimum: 10}
  validates :instructions, presence: true
  validates :pics_to_upload, presence: { message: "Rating is mandatory, please specify one" },
                              numericality: { only_integer: true,
                              greater_than_or_equal_to: 0
                              }
  validates :pics_to_post, presence: { message: "Rating is mandatory, please specify one" },
                              numericality: { only_integer: true,
                              greater_than_or_equal_to: 0
                              }
  validates :budget, presence: { message: "Rating is mandatory, please specify one" },
                            numericality: { only_integer: true,
                            greater_than_or_equal_to: 0
                            }
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :find_campaign, only: [:show, :edit, :update]

  def index
    @campaigns = policy_scope(Campaign)
    @paid_jobs = Campaign.where(reward_type: "Paid Job")
    @local_swaps = Campaign.where(reward_type: "Local Swap")
    @markers = Gmaps4rails.build_markers(@local_swaps) do |campaign, marker|
      marker_url = view_context.image_path("marker.png")
      marker.lat campaign.latitude
      marker.lng campaign.longitude
      marker.picture({
        url: marker_url,
        width: 32,
        height: 32
       })
      marker.infowindow render_to_string(:partial => "/campaigns/map_box", locals: {campaign: campaign})
    end
  end

  def show
    authorize @campaign
    @application = Application.new
    @marker = Gmaps4rails.build_markers(@campaign) do |campaign, marker|
      marker_url = view_context.image_path("marker.png")
      marker.lat campaign.latitude
      marker.lng campaign.longitude
      marker.picture({
        url: marker_url,
        width: 32,
        height: 32
       })
      marker.infowindow render_to_string(:partial => "/campaigns/map_box", locals: {campaign: campaign})
    end
  end

  def new
    @campaign = Campaign.new
    authorize @campaign
  end

  def create
    @business = Business.find_by_user_id(current_user)
    @campaign = Campaign.new(campaign_params)
    @campaign.business = @business
    authorize @campaign
    if @campaign.save
      flash[:notice] = "Successfully created #{@campaign.title}"
      redirect_to campaign_path(@campaign)
    else
      flash[:alert] = "Failed to create #{@campaign.title}"
      render :new
    end
  end

  def edit
    authorize @campaign
  end

  def update
    authorize @campaign
    @campaign.update(campaign_params)
    redirect_to campaign_path(@campaign)
  end

  private

  def campaign_params
    params.require(:campaign).permit(:target_location, :reward_type, :title, :product, :goal, :start_time, :end_time, :description, :instructions, :budget, :pics_to_upload, :pics_to_post, :photo, :photo_cache)
  end

  def find_campaign
    @campaign = Campaign.find(params[:id])
  end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/_form.html.erb
<%= simple_form_for(@campaign) do |f| %>
  <%= f.error_notification %>

  <%= f.input :reward_type, collection: [ "Local Swap", "Paid Job"], as: :radio_buttons, item_wrapper_tag: nil, item_wrapper_class: nil, :checked => "Local Swap" %>
  <%= f.input :target_location, label: 'Target Location (if local)', placeholder: '3 Rue de la Paix, 75002 Paris, France' %>
  <%= f.input :title %>
  <%= f.input :product %>
  <%= f.input :goal %>
  <%= f.input :budget %>
  <%= f.input :start_time %>
  <%= f.input :end_time %>
  <%= f.input :description %>
  <%= f.input :instructions %>
  <%= f.input :pics_to_upload %>
  <%= f.input :pics_to_post %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <div class="text-center">
  <%= f.button :submit, class: "brand-button" %>
  </div>
<% end %>

app/views/campaigns/_map_box.html.erb
<div class="map_box text-center slideUp">
  <h3><%= campaign.title %></h3>
  <p><%= campaign.product %></p>
  <p><%= campaign.target_location %></p>
  <%= link_to "See", campaign, class: "btn btn-warning" %>
</div>

app/views/campaigns/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">

      <div class="text-center">
      <h1>Edit your campaign</h1>
      </div>

      <div class="form-container">
      <%= render 'form' %>
      </div>

      <hr>

      <div class="text-center">
      <%= link_to 'Return to main page', root_path %>
      </div>

    </div>
  </div>
</div>

app/views/campaigns/index.html.erb
<div>

  <div class="tabs">
    <a class="tab active" data-target="#local_swaps_wrapper">
      <h3><i class="fa fa-compass"></i>  Local Swaps</h3>
    </a>
    <a class="tab" data-target="#paid_jobs_wrapper">
      <h3><i class="fa fa-line-chart"></i>  Paid Jobs</h3>
    </a>
  </div>

  <div id="local_swaps_wrapper" class="tab-content">
    <div id="local_swaps_view">
      <div class="fluid-container">

        <div class="row nomargin">
          <div class="col-xs-12 col-md-7 leftcol">

            <div class="row">

              <div class="local_swaps">
                <% @local_swaps.each do |campaign| %>
                <div class="col-xs-8 col-xs-offset-2">
                  <div class="campaign-card fadeIn">
                    <p><%= campaign.title%></p>
                    <div class="campaign-card-banner" style="background-image: url(<%= cl_image_path campaign.photo %>);"></div>
                    <p> #<%= (campaign.product).split.join %> </p>
                    <hr class="line">
                    <%= link_to campaign_path(campaign), class: "campaign-link" do %>
                    @Check Da Campaign
                    <% end %>

                  </div>
                </div>
                <% end %>
              </div>

            </div>

          </div>
          <div class="col-xs-12 col-md-5 rightcol">

            <div id="map"></div>

          </div>
        </div>

      </div>
    </div>
  </div>

  <div id="paid_jobs_wrapper" class="tab-content hidden">
    <div id="paid_jobs_view">
      <div class="fluid-container">

        <div class="row">
          <div class="col-xs-12 col-sm-8 col-sm-offset-2">

            <div class="paid_jobs">

              <div class="row">
                <% @paid_jobs.each do |campaign| %>
                <div class="col-xs-8 col-xs-offset-2">
                  <div class="campaign-card">
                    <p><%= campaign.title%></p>
                    <div class="campaign-card-banner" style="background-image: url(<%= cl_image_path campaign.photo %>);"></div>
                    <p> #<%= (campaign.product).split.join %> </p>
                    <hr class="line">
                    <%= link_to campaign_path(campaign), class: "campaign-link" do %>
                    @Check Da Campaign
                    <% end %>
                  </div>
                </div>
                <% end %>
              </div>

            </div>

          </div>
        </div>
      </div>
    </div>
  </div>

</div>

<% content_for(:after_js) do %>
<%= javascript_tag do %>
$(document).on('ready', function() {
handler = Gmaps.build('Google');
handler.buildMap({ provider: {
scrollwheel: false}, internal: { id: 'map' } }, function(){
markers = handler.addMarkers(<%= raw @markers.to_json %>);
handler.bounds.extendWith(markers);
handler.fitMapToBounds();});})
<% end %>
<% end %>

<%= javascript_include_tag "//maps.google.com/maps/api/js?v=3.18&client=&key=AIzaSyD2QUpbXmjF_9rvcIUqQZKMOShKpF8S64I&libraries=geometry&language=&hl=&region=" %>

app/views/campaigns/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">

      <div class="text-center">
      <h3>Create your campaign</h3>
      </div>

      <div class="form-container">
      <%= render 'form' %>
      </div>

      <hr>

      <div class="text-center">
      <%= link_to 'Return to main page', root_path %>
      </div>

    </div>
  </div>
</div>

app/views/campaigns/show.html.erb
<div class="insta-influencer-card-container">
      <div class="insta-pic-business-show" style="background-image: linear-gradient(rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4)), url('<%= @campaign.photo %>');">
        <div class='insta-budget-container'>
          <div class='insta-budget'>
            <%= @campaign.budget %>€
          </div>
        </div>
        <div class='insta-product'><%=@campaign.product%></div>
      </div>
      <div class="business-insta-description">
        <div class="insta-title-container">
          <div class='insta-title'>
            <%= @campaign.title %>
          </div>
           <div>
          <% if policy(@campaign).update? %>
          <%= link_to 'Edit', edit_campaign_path(@campaign), class:"btn action-button" %>
          <% end %>
          </div>
        </div>

        <div class='insta-instruction'>
          <%=@campaign.instructions%>
        </div>
        <div class='insta-timeline'>
          <div class='insta-timeline-start'>
            <i class="fa fa-flag-o insta-flag" aria-hidden="true"></i> <%= @campaign.start_time %>
          </div>
          <div class="insta-timeline-line">
            <hr class="insta-timeline-color">
          </div>
          <div class='insta-timeline-end'>
            <i class="fa fa-flag-checkered insta-flag" aria-hidden="true"></i><%= @campaign.end_time %>
          </div>
        </div>
        <div class="insta-obligations">
          You will have to upload <strong><%=@campaign.pics_to_upload%></strong> pictures, the brand will select <strong><%=@campaign.pics_to_post%></strong> pictures for you to post on instagram.
        </div>

        <div class='insta-appliers-title'></div>
        <div class='insta-appliers'>
          <% if @campaign.reward_type == "Local Swap" %>
            <div id="small-map"></div>
          <% end %>
        </div>
      </div>

      <% if user_signed_in? && current_user.influencer && @campaign.reward_type == "Paid Job"%>

       <div class="apply-box">
         <h3>Apply</h3>
         <%= render 'applications/application_form' %>
       </div>

      <% end %>

  </div>

<% content_for(:after_js) do %>
<%= javascript_tag do %>
$(document).on('ready', function() {
handler = Gmaps.build('Google');
handler.buildMap({ provider: {
scrollwheel: false}, internal: { id: 'small-map' } }, function(){
marker = handler.addMarkers(<%= raw @marker.to_json %>);
handler.bounds.extendWith(marker);
handler.fitMapToBounds();});})
<% end %>
<% end %>

<%= javascript_include_tag "//maps.google.com/maps/api/js?v=3.18&client=&key=AIzaSyAWTD7XXgfWzV60HCDVLL-71xV1yoH6lBQ&libraries=geometry&language=&hl=&region=" %>
<%= javascript_include_tag "https://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" %>